emeraldview_name:          Encyclopedia of the Founders and Builders of Israel
institution_url:           http://www.tourolib.org/
institution_name:          Touro College Libraries

greenstone_collection_dir: /www/websites/collect

default_theme: default
default_language: en
languages:
  en: English

collections:
  tidhar:
    active: true
    theme: tidhar
    paged_continuous: true
    send_email_to: "michoel.ronn@touro.edu"
    solr_host: localhost
    solr_simple_qt: dismaxev
    discoveries:
      Haaretz:
        It is difficult to overstate the significance of this project.
      David Hacohen, Tel Aviv:
        Tidhar's Encyclopedia online is like an 'oracle' to me.
      batyama:
        I never saw a picture of my great great grandfather &ndash; and here he was.
    slug_metadata_elements:
      - Volume
    search_results_format_function: |
      return L10n::vsprintf( 'Page %s', array( $node->getField( 'Title' ) ) );
    classifiers:
      CL1:
        cache: true
        format_function: |
          return '[a]' . L10n::vsprintf( 'Volume %s', array( $node->getField( 'Volume' ) ) ) . '[/a]';
      CL2:
        load_ajax: true
        cache: true
        dir: rtl
        format:
          leaf: "[Subject]"

